all:
  children:
    webservers:
      hosts:
        37.152.181.201:
          ansible_user: ubuntu
          ansible_port: 22
          copy:
           src: ./test.txt
           dest: /tmp/test-file-1.txt

    dbservers:
      hosts:
        194.5.206.94:
          ansible_user: ubuntu
          ansible_port: 22
